-- Tạo database
CREATE DATABASE IF NOT EXISTS qlct
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;
USE qlct;

-- Bảng KHACHHANG
CREATE TABLE `KHACHHANG` (
  `makh` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `tenkh` VARCHAR(100) NOT NULL,
  `email` VARCHAR(150) NOT NULL UNIQUE,
  `matkhau` VARCHAR(255) NOT NULL,
  `hinhanh` VARCHAR(255) DEFAULT NULL,
  `quyen` VARCHAR(20) NOT NULL DEFAULT 'user',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Bảng DMCHITIEU
CREATE TABLE `DMCHITIEU` (
  `machitieu` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `makh` INT NOT NULL,
  `tendanhmuc` VARCHAR(100) NOT NULL,
  `loai` ENUM('income','expense') NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `FK_DMCHITIEU_KHACHHANG` FOREIGN KEY (`makh`) REFERENCES `KHACHHANG`(`makh`)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Bảng DSCHITIEU
CREATE TABLE `DSCHITIEU` (
  `maloaichitieu` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `makh` INT NOT NULL,
  `machitieu` INT NOT NULL,
  `ngaychitieu` DATE NOT NULL,
  `noidung` VARCHAR(255) NOT NULL,
  `loai` ENUM('income','expense') NOT NULL,
  `sotien` DECIMAL(18,2) NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `FK_DSCHITIEU_KHACHHANG` FOREIGN KEY (`makh`) REFERENCES `KHACHHANG`(`makh`)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_DSCHITIEU_DMCHITIEU` FOREIGN KEY (`machitieu`) REFERENCES `DMCHITIEU`(`machitieu`)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Bảng GIAODICH
CREATE TABLE `GIAODICH` (
  `magd` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `makh` INT NOT NULL,
  `machitieu` INT NOT NULL,
  `sotien` DECIMAL(18,2) NOT NULL,
  `loai` ENUM('income','expense') NOT NULL,
  `ngaygiaodich` DATE NOT NULL,
  `ghichu` VARCHAR(255) DEFAULT NULL,
  `anhhoadon` VARCHAR(255) DEFAULT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `FK_GIAODICH_KHACHHANG` FOREIGN KEY (`makh`) REFERENCES `KHACHHANG`(`makh`)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_GIAODICH_DMCHITIEU` FOREIGN KEY (`machitieu`) REFERENCES `DMCHITIEU`(`machitieu`)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Bảng NGANSACH
CREATE TABLE `NGANSACH` (
  `mangansach` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `makh` INT NOT NULL,
  `machitieu` INT NOT NULL,
  `amount` DECIMAL(18,2) NOT NULL,
  `chuky` ENUM('week','month','year') NOT NULL,
  `ngaybatdau` DATE NOT NULL,
  `ngayketthuc` DATE NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `FK_NGANSACH_KHACHHANG` FOREIGN KEY (`makh`) REFERENCES `KHACHHANG`(`makh`)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_NGANSACH_DMCHITIEU` FOREIGN KEY (`machitieu`) REFERENCES `DMCHITIEU`(`machitieu`)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Bảng BANGNO
CREATE TABLE `BANGNO` (
  `mabangno` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `makh` INT NOT NULL,
  `sotienno` DECIMAL(18,2) NOT NULL,
  `loai` ENUM('lend','borrow') NOT NULL,
  `nguoilienquan` VARCHAR(100) NOT NULL,
  `ngaydaohan` DATE NOT NULL,
  `trangthai` ENUM('pending','paid') NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `FK_BANGNO_KHACHHANG` FOREIGN KEY (`makh`) REFERENCES `KHACHHANG`(`makh`)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Bảng TIETKIEM
CREATE TABLE `TIETKIEM` (
  `matk` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `makh` INT NOT NULL,
  `muctieu` VARCHAR(150) NOT NULL,
  `sotiencandat` DECIMAL(18,2) NOT NULL,
  `sotiendatietkiem` DECIMAL(18,2) NOT NULL DEFAULT 0,
  `hanmuctieu` DATE NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `FK_TIETKIEM_KHACHHANG` FOREIGN KEY (`makh`) REFERENCES `KHACHHANG`(`makh`)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Bảng THONGBAO
CREATE TABLE `THONGBAO` (
  `matb` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `makh` INT NOT NULL,
  `noidung` VARCHAR(255) NOT NULL,
  `loai` ENUM('warning','reminder','info') NOT NULL,
  `trangthai` BOOLEAN NOT NULL DEFAULT 0,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT `FK_THONGBAO_KHACHHANG` FOREIGN KEY (`makh`) REFERENCES `KHACHHANG`(`makh`)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
