DROP DATABASE IF EXISTS qlct;
CREATE DATABASE IF NOT EXISTS qlct CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE qlct;

-- Bảng KHACHHANG
CREATE TABLE KHACHHANG (
    makh INT AUTO_INCREMENT PRIMARY KEY,
    tenkh VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    matkhau VARCHAR(255) NOT NULL,
    hinhanh VARCHAR(255),
    quyen VARCHAR(20) DEFAULT 'user',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Bảng DMCHITIEU
CREATE TABLE DMCHITIEU (
    machitieu INT AUTO_INCREMENT PRIMARY KEY,
    makh INT NOT NULL,
    tendanhmuc VARCHAR(100) NOT NULL,
    loai ENUM('income','expense') NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (makh) REFERENCES KHACHHANG(makh)
);

-- Bảng DSCHITIEU
CREATE TABLE DSCHITIEU (
    maloaichitieu INT AUTO_INCREMENT PRIMARY KEY,
    makh INT NOT NULL,
    machitieu INT NOT NULL,
    ngaychitieu DATE NOT NULL,
    noidung VARCHAR(255) NOT NULL,
    loai ENUM('income','expense') NOT NULL,
    sotien DECIMAL(18,2) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (makh) REFERENCES KHACHHANG(makh),
    FOREIGN KEY (machitieu) REFERENCES DMCHITIEU(machitieu)
);

-- Bảng DSTHUNHAP
CREATE TABLE DSTHUNHAP (
    mathunhap INT AUTO_INCREMENT PRIMARY KEY,
    makh INT NOT NULL,
    machitieu INT NOT NULL,
    ngaythunhap DATE NOT NULL,
    noidung VARCHAR(255) NOT NULL,
    loai ENUM('income','expense') DEFAULT 'income',
    sotien DECIMAL(18,2) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (makh) REFERENCES KHACHHANG(makh),
    FOREIGN KEY (machitieu) REFERENCES DMCHITIEU(machitieu)
);

-- Bảng GIAODICH
CREATE TABLE GIAODICH (
    magd INT AUTO_INCREMENT PRIMARY KEY,
    makh INT NOT NULL,
    machitieu INT NOT NULL,
    sotien DECIMAL(18,2) NOT NULL,
    loai ENUM('income','expense') NOT NULL,
    ngaygiaodich DATE NOT NULL,
    ghichu VARCHAR(255),
    anhhoadon VARCHAR(255),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (makh) REFERENCES KHACHHANG(makh),
    FOREIGN KEY (machitieu) REFERENCES DMCHITIEU(machitieu)
);

-- Bảng NGANSACH
CREATE TABLE NGANSACH (
    mangansach INT AUTO_INCREMENT PRIMARY KEY,
    makh INT NOT NULL,
    machitieu INT NOT NULL,
    ngay DATE NOT NULL,
    ngansach DECIMAL(18,2) NOT NULL,
    dachi DECIMAL(18,2) DEFAULT 0,
    chenhlech DECIMAL(18,2) GENERATED ALWAYS AS (ngansach - dachi) STORED,
    trangthai ENUM('under_budget','on_budget','over_budget') DEFAULT 'on_budget',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (makh) REFERENCES KHACHHANG(makh),
    FOREIGN KEY (machitieu) REFERENCES DMCHITIEU(machitieu)
);

-- Bảng BANGNO
CREATE TABLE BANGNO (
    mabangno INT AUTO_INCREMENT PRIMARY KEY,
    makh INT NOT NULL,
    sotienno DECIMAL(18,2) NOT NULL,
    loai ENUM('lend','borrow') NOT NULL,
    nguoilienquan VARCHAR(100) NOT NULL,
    ngaydaohan DATE NOT NULL,
    trangthai ENUM('pending','paid') NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (makh) REFERENCES KHACHHANG(makh)
);

-- Bảng TIETKIEM
CREATE TABLE TIETKIEM (
    matk INT AUTO_INCREMENT PRIMARY KEY,
    makh INT NOT NULL,
    muctieu VARCHAR(150) NOT NULL,
    sotiencandat DECIMAL(18,2) NOT NULL,
    sotiendatietkiem DECIMAL(18,2) DEFAULT 0,
    hanmuctieu DATE NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (makh) REFERENCES KHACHHANG(makh)
);

-- Bảng THONGBAO
CREATE TABLE THONGBAO (
    matb INT AUTO_INCREMENT PRIMARY KEY,
    makh INT NOT NULL,
    noidung VARCHAR(255) NOT NULL,
    loai ENUM('warning','reminder','info') NOT NULL,
    trangthai BOOLEAN DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (makh) REFERENCES KHACHHANG(makh)
);
